# THIS IS AN EXAMPLE ON HOW YOU SHOULD CONFIGURE YOUR hugo.toml
# See this hugo.toml in action at https://github.com/1bl4z3r/hermit-V2/blob/staging/hugo.toml
# Example Site is Staging branch, acessible at https://github.com/1bl4z3r/hermit-V2/tree/staging
# To see what each config does, refer to https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/
# Open Issue or Pull Request at https://github.com/1bl4z3r/hermit-V2

name = "CoreDumps"
baseURL = "https://blog.coredumps.io"
theme = "hermit-v2"

languageCode = "en-gb"

title = "CoreDumps"
enableGitInfo = false

pygmentsCodefences  = true
pygmentsUseClasses  = true
#hasCJKLanguage = true

rssLimit = 10

copyright = "Marcin Kłopotek"
enableEmoji = true

googleAnalytics = "UA-16526881"
disqusShortname = "coredumps"

[params.author]
  name = "Marcin Kłopotek"
  about = "about-me.md"

[blackfriday]
#  hrefTargetBlank = true
#  noreferrerLinks = true
#  nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "This is where CoreDumps - by Marcin Kłopotek"
#  images = []
  themeColor = "#494f5c"

  homeSubtitle = "Years of coding distilled into a journey of sharing and discovery."

  footerCopyright = "This is where CoreDumps"
  bgImg = "images/coredumps-logo-1.png"
  gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = true

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true
  global_mathjax = false
  readTime = true
  readTimeSeparator = "⏲ Reading Time:"
  # legacyLayout = false
  shareSocial = true

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/marcinklopotek/"
  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/goostleek"


[menu]
  [[menu.main]]
    name = "📝 Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "👋 About Me "
    url = "about-me/"
    weight = 20
